export const projects = [
  {
    title: 'Grid app',
    description: "The project to design custom made grid-based framework using CSS Grid.",
      image: '/images/gridhome.png',
      tags: ['CSS Grid'],
    source: 'https://github.com/IBUNHABIBU/GRID-FRAMEWORK',
    visit: 'https://rawcdn.githack.com/IBUNHABIBU/GRID-FRAMEWORK/44ef6cc3f2ca5cede15c1865492901b6c4c680b4/index.html',
    id: 0,
  },
  {
    title: 'Life Style Article',
    description:"In this project users will be posting their articles with background images and ability to vote for a good article and the most voted article is placed on the front page with the big Image.",
    image: '/images/Homepage.png',
    tags: ['Ruby on rails', 'RSpec'],
    source: 'https://github.com/IBUNHABIBU/lifestyle_articles',
    visit: 'https://lifestylearticle.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Newsweek Web Clone',
    description: "This is a clone of the newsweek website.",
      image: '/images/newsweekhome.png',
      tags: ['HTML', 'CSS'],
    source: '#',
    visit: '#',
    id: 2,
  },
  {
    title: 'Recipes App',
    description: "A browsable list of items that you can filter and access to the details of one item. All data are meals recipes that come from TheMealDb API",
    image: '/images/recipes.png',
    tags: ['React', 'Redux'],
    source: 'https://https://github.com/IBUNHABIBU/catalogue_of_recipes',
    visit: 'https://slm-foodrecipe.herokuapp.com/',
    id: 3,
  },
  {
    title: 'Social app',
    description: "A social media application where user may signup connect with friends, posting and liking friends post.",
    image: '/images/social.png',
    tags: ['Ruby on Rails', 'Rspec'],
    source: 'https://github.com/IBUNHABIBU/ror-social-scaffold',
    visit: 'https://sm-social-app.herokuapp.com/',
    id: 4,
  },
  {
    title: 'Weather app',
    description: "Is the Javascript quiz to implement the concept of API. I made a simple page to fetch for weather data.",
    image: '/images/weather.png',
    tags: ['Javascript', 'Webpack', 'OpenWeatherAPI'],
    source: 'https://github.com/IBUNHABIBU/weather-app',
    visit: 'https://google.com',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey', },
  { year: 2020, text: 'Joined a coding school called Microverse', },
  { year: 2021, text: 'Completed my learning journey at Microverse', },
  { year: 2022, text: 'Build projects and search for more opportunities', },
];